---
title: "MSD-Data-Manager"
author: "Kang Dong"
date: '2023-05-01'
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Introduction

# Objective

# Shiny App
```{r}
# Library
library(tidyverse)
library(magrittr)
library(readxl)
library(shiny)
library(DT)
library(plotly)



# Support Function
# 1) Date
today <- function() format(Sys.Date(), "%Y%m%d")
now <- function() format(Sys.time(), "%H%M")

# 2) Make directory
make_dir <- function(x) {
    if(!dir.exists(x)) dir.create(x, recursive = TRUE)
    return(x)
}



# Directory
project_dir <- "/Users/KangDong/Desktop/MSD-Data-Manager" # Change to local project directory
input_dir <- file.path(project_dir, "input") %>% make_dir
output_dir <- file.path(project_dir, "output") %>% make_dir
log_dir <- file.path(project_dir, "log") %>% make_dir



# Files
splman_file <- list.files(input_dir, pattern = "Sample_Manifest")
splman <- read_excel(path = file.path(input_dir, splman_file), sheet = "sample manifest")



# Running App
library(shiny)

ui <- fluidPage(
  # title
  titlePanel("MSD Data Manager"),
  
  # sidebar layout
  sidebarLayout(
    sidebarPanel(
      # Data file
      fileInput("data", "Choose your data file", accept = ".csv", multiple = TRUE),
      # Standard file
      fileInput("standard", "Choose your standard file", accept = ".csv", multiple = TRUE),
      # Sample manifest file
      fileInput("splman", "Choose your sample manifest file", accept = ".xlsx", multiple = FALSE)
    ),
    
    mainPanel(
      tabsetPanel(
        tabPanel("CV", plotlyOutput("cv")),
        tabPanel("Standard", plotlyOutput("standard")),
        tabPanel("Data", dataTableOutput("data_table"))
      )

    )
    
  )
)
  


server <- function(input, output, session) {
  # Data file
    output$data_table <- renderDataTable({
      
        data_files <- input$data$datapath %>%
          set_names(input$data$name)
        
        
        if (length(data_files) == 0) {
          return(NULL)
          }
        
        map(data_files, ~ read.csv(.x, skip = 1)) %>%
          bind_rows(.id = "Filename")

    })
  

  

}

shinyApp(ui, server)



```

# Process MSD data
